/**
 * Sample recipes for initial data
 * Popular recipes to seed the database
 */

export const sampleRecipes = [
  {
    title: "Spaghetti Bolognese",
    description: "Classic Italian pasta with rich meat sauce",
    servings: 4,
    prepTime: 15,
    cookTime: 30,
    category: "dinner",
    tags: ["italian", "quick"],
    ingredients: [
      { name: "Spaghetti", amount: 400, unit: "g" },
      { name: "Ground beef", amount: 500, unit: "g" },
      { name: "Tomato sauce", amount: 400, unit: "ml" },
      { name: "Onion", amount: 1, unit: "piece" },
      { name: "Garlic", amount: 3, unit: "piece" },
      { name: "Olive oil", amount: 2, unit: "tbsp" },
      { name: "Salt and pepper", amount: 1, unit: "tsp" },
    ],
    steps: [
      { number: 1, description: "Heat olive oil in a large pan over medium heat" },
      { number: 2, description: "Sauté chopped onion and garlic until fragrant" },
      { number: 3, description: "Add ground beef and cook until browned" },
      { number: 4, description: "Stir in tomato sauce and simmer for 20 minutes" },
      { number: 5, description: "Cook spaghetti according to package directions" },
      { number: 6, description: "Serve pasta topped with sauce" },
    ],
  },
  {
    title: "Chicken Stir Fry",
    description: "Quick and healthy Asian-inspired dish",
    servings: 3,
    prepTime: 20,
    cookTime: 15,
    category: "dinner",
    tags: ["asian", "quick", "healthy"],
    ingredients: [
      { name: "Chicken breast", amount: 500, unit: "g" },
      { name: "Bell peppers", amount: 2, unit: "piece" },
      { name: "Broccoli", amount: 300, unit: "g" },
      { name: "Soy sauce", amount: 3, unit: "tbsp" },
      { name: "Garlic", amount: 4, unit: "piece" },
      { name: "Ginger", amount: 1, unit: "tbsp" },
      { name: "Vegetable oil", amount: 2, unit: "tbsp" },
    ],
    steps: [
      { number: 1, description: "Cut chicken into bite-sized pieces" },
      { number: 2, description: "Heat oil in a wok or large pan over high heat" },
      { number: 3, description: "Stir fry chicken until cooked through" },
      { number: 4, description: "Add vegetables and stir fry for 5-7 minutes" },
      { number: 5, description: "Add soy sauce, garlic, and ginger" },
      { number: 6, description: "Toss everything together and serve hot" },
    ],
  },
  {
    title: "Chocolate Chip Cookies",
    description: "Homemade cookies with melting chocolate chips",
    servings: 24,
    prepTime: 15,
    cookTime: 12,
    category: "dessert",
    tags: ["sweet", "baking"],
    ingredients: [
      { name: "Butter", amount: 225, unit: "g" },
      { name: "Brown sugar", amount: 200, unit: "g" },
      { name: "Egg", amount: 2, unit: "piece" },
      { name: "Vanilla extract", amount: 1, unit: "tsp" },
      { name: "Flour", amount: 280, unit: "g" },
      { name: "Baking soda", amount: 1, unit: "tsp" },
      { name: "Chocolate chips", amount: 340, unit: "g" },
    ],
    steps: [
      { number: 1, description: "Preheat oven to 375°F (190°C)" },
      { number: 2, description: "Cream butter and brown sugar together" },
      { number: 3, description: "Beat in eggs and vanilla extract" },
      { number: 4, description: "Mix flour and baking soda, then combine with butter mixture" },
      { number: 5, description: "Fold in chocolate chips" },
      { number: 6, description: "Drop spoonfuls onto baking sheet and bake 10-12 minutes" },
    ],
  },
  {
    title: "Greek Salad",
    description: "Fresh and healthy Mediterranean salad",
    servings: 2,
    prepTime: 10,
    cookTime: 0,
    category: "lunch",
    tags: ["healthy", "vegetarian", "quick"],
    ingredients: [
      { name: "Cucumber", amount: 1, unit: "piece" },
      { name: "Tomato", amount: 2, unit: "piece" },
      { name: "Red onion", amount: 0.5, unit: "piece" },
      { name: "Feta cheese", amount: 200, unit: "g" },
      { name: "Kalamata olives", amount: 100, unit: "g" },
      { name: "Olive oil", amount: 3, unit: "tbsp" },
      { name: "Lemon juice", amount: 2, unit: "tbsp" },
    ],
    steps: [
      { number: 1, description: "Chop cucumber, tomato, and red onion" },
      { number: 2, description: "Combine vegetables in a large bowl" },
      { number: 3, description: "Add feta cheese and olives" },
      { number: 4, description: "Drizzle with olive oil and lemon juice" },
      { number: 5, description: "Toss gently and season with salt and pepper" },
      { number: 6, description: "Serve immediately" },
    ],
  },
  {
    title: "Pancakes",
    description: "Fluffy breakfast pancakes",
    servings: 4,
    prepTime: 10,
    cookTime: 15,
    category: "breakfast",
    tags: ["quick", "breakfast"],
    ingredients: [
      { name: "Flour", amount: 200, unit: "g" },
      { name: "Milk", amount: 240, unit: "ml" },
      { name: "Egg", amount: 2, unit: "piece" },
      { name: "Baking powder", amount: 2, unit: "tsp" },
      { name: "Sugar", amount: 2, unit: "tbsp" },
      { name: "Butter", amount: 50, unit: "g" },
      { name: "Salt", amount: 0.5, unit: "tsp" },
    ],
    steps: [
      { number: 1, description: "Mix flour, baking powder, sugar, and salt" },
      { number: 2, description: "Whisk milk, eggs, and melted butter together" },
      { number: 3, description: "Combine wet and dry ingredients until just mixed" },
      { number: 4, description: "Heat a griddle or pan over medium heat" },
      { number: 5, description: "Pour batter and cook until bubbles form" },
      { number: 6, description: "Flip and cook until golden brown" },
    ],
  },
];
